import { Grant } from "./types";

export const grants: Grant[] = [
  {
    id: "sba-7a",
    name: "SBA 7(a) Loan Program",
    agency: "U.S. Small Business Administration",
    description:
      "The SBA's primary program for providing financial assistance to small businesses. Funds can be used for working capital, equipment, real estate, and business acquisition.",
    amountMin: 25000,
    amountMax: 5000000,
    deadline: "2026-12-31",
    eligibility: {
      industries: ["technology", "retail", "manufacturing", "healthcare", "food", "services", "construction", "agriculture"],
      maxEmployees: 500,
      maxRevenue: 7500000,
      states: "all",
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://www.sba.gov/funding-programs/loans/7a-loans",
    tips: [
      "Prepare a detailed business plan with financial projections",
      "Show strong personal credit history (680+ recommended)",
      "Demonstrate cash flow sufficient to service the loan",
      "Have collateral ready to present",
    ],
    commonQuestions: [
      "Describe your business and its primary products or services.",
      "What is the purpose of the requested funding?",
      "Provide a 3-year financial projection for your business.",
    ],
    category: "SBA",
  },
  {
    id: "sba-microloan",
    name: "SBA Microloan Program",
    agency: "U.S. Small Business Administration",
    description:
      "Provides small, short-term loans to small businesses and certain not-for-profit childcare centers. Designed for startups and growing small businesses needing smaller amounts of capital.",
    amountMin: 500,
    amountMax: 50000,
    deadline: "2026-12-31",
    eligibility: {
      industries: ["technology", "retail", "manufacturing", "healthcare", "food", "services", "construction", "agriculture", "education", "nonprofit"],
      maxEmployees: 50,
      maxRevenue: 1000000,
      states: "all",
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://www.sba.gov/funding-programs/loans/microloans",
    tips: [
      "Ideal for startups with limited credit history",
      "Average microloan is about $13,000",
      "Must apply through SBA-approved intermediary lenders",
      "Business training may be required alongside the loan",
    ],
    commonQuestions: [
      "How will the microloan funds be used in your business?",
      "Describe your experience in this industry.",
      "What is your plan for repaying this loan?",
    ],
    category: "SBA",
  },
  {
    id: "sba-community-advantage",
    name: "SBA Community Advantage Loan",
    agency: "U.S. Small Business Administration",
    description:
      "Designed to help mission-focused lenders serve small businesses in underserved communities. Focuses on businesses in low-to-moderate income areas.",
    amountMin: 50000,
    amountMax: 350000,
    deadline: "2026-12-31",
    eligibility: {
      industries: ["technology", "retail", "manufacturing", "healthcare", "food", "services", "construction"],
      maxEmployees: 100,
      maxRevenue: 3000000,
      states: "all",
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://www.sba.gov/funding-programs/loans/community-advantage",
    tips: [
      "Best for businesses in underserved markets",
      "Lower barrier to entry than traditional 7(a) loans",
      "Community development focus strengthens your application",
      "Highlight community impact in your narrative",
    ],
    commonQuestions: [
      "How does your business serve the local community?",
      "Describe the economic impact your business has in your area.",
      "What barriers have you faced in accessing traditional financing?",
    ],
    category: "SBA",
  },
  {
    id: "sbir-phase1",
    name: "SBIR Phase I",
    agency: "Small Business Innovation Research",
    description:
      "Federal program that encourages small businesses to engage in R&D with potential for commercialization. Phase I establishes technical merit and feasibility.",
    amountMin: 50000,
    amountMax: 275000,
    deadline: "2026-06-15",
    eligibility: {
      industries: ["technology", "healthcare", "manufacturing", "agriculture", "energy"],
      maxEmployees: 500,
      maxRevenue: null,
      states: "all",
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://www.sbir.gov/about",
    tips: [
      "Focus on innovation and technical merit",
      "Must be a for-profit company with 500 or fewer employees",
      "Principal investigator must be primarily employed by the company",
      "Address a specific government R&D need or topic",
    ],
    commonQuestions: [
      "Describe the technical innovation and its significance.",
      "What is the commercial potential of your technology?",
      "Outline your research plan and key milestones for Phase I.",
    ],
    category: "SBIR/STTR",
  },
  {
    id: "sbir-phase2",
    name: "SBIR Phase II",
    agency: "Small Business Innovation Research",
    description:
      "Continuation of Phase I for R&D projects that demonstrated feasibility. Focuses on developing prototypes and moving toward commercialization.",
    amountMin: 500000,
    amountMax: 1500000,
    deadline: "2026-09-30",
    eligibility: {
      industries: ["technology", "healthcare", "manufacturing", "agriculture", "energy"],
      maxEmployees: 500,
      maxRevenue: null,
      states: "all",
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://www.sbir.gov/about",
    tips: [
      "Requires successful Phase I completion",
      "Demonstrate clear path to commercialization",
      "Include customer discovery and market validation",
      "Budget should reflect prototype development costs",
    ],
    commonQuestions: [
      "Summarize your Phase I results and findings.",
      "How will Phase II advance the technology toward commercialization?",
      "Describe your target market and go-to-market strategy.",
    ],
    category: "SBIR/STTR",
  },
  {
    id: "sttr-phase1",
    name: "STTR Phase I",
    agency: "Small Business Technology Transfer",
    description:
      "Similar to SBIR but requires formal collaboration between a small business and a research institution. Focuses on technology transfer from research to market.",
    amountMin: 50000,
    amountMax: 275000,
    deadline: "2026-06-15",
    eligibility: {
      industries: ["technology", "healthcare", "manufacturing", "energy"],
      maxEmployees: 500,
      maxRevenue: null,
      states: "all",
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://www.sbir.gov/about/about-sttr",
    tips: [
      "Must partner with a research institution (university, federal lab)",
      "Research institution must perform at least 30% of the work",
      "Small business performs at least 40% of the work",
      "Intellectual property agreement required between partners",
    ],
    commonQuestions: [
      "Describe the research institution partnership and each party's role.",
      "What is the technical innovation being developed?",
      "How will the intellectual property be managed between partners?",
    ],
    category: "SBIR/STTR",
  },
  {
    id: "mbda-grants",
    name: "MBDA Business Center Grants",
    agency: "Minority Business Development Agency",
    description:
      "Provides funding to minority-owned businesses through a network of business centers. Offers access to capital, contracts, and markets.",
    amountMin: 10000,
    amountMax: 300000,
    deadline: "2026-08-31",
    eligibility: {
      industries: ["technology", "retail", "manufacturing", "healthcare", "food", "services", "construction", "energy"],
      maxEmployees: 500,
      maxRevenue: 5000000,
      states: "all",
      minorityOwned: true,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: true,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://www.mbda.gov/grants",
    tips: [
      "Must be a minority-owned business (at least 51% ownership)",
      "Demonstrate growth potential and job creation",
      "Connect with your local MBDA Business Center first",
      "Emphasize community economic impact",
    ],
    commonQuestions: [
      "Describe your business and its minority ownership structure.",
      "How will this funding help your business grow?",
      "What is your plan for job creation in the community?",
    ],
    category: "Minority-Owned",
  },
  {
    id: "nmsdc-grants",
    name: "NMSDC Emerging Young Entrepreneurs Grant",
    agency: "National Minority Supplier Development Council",
    description:
      "Supports young minority entrepreneurs (ages 18-35) with grants for business development, training, and mentorship opportunities.",
    amountMin: 5000,
    amountMax: 25000,
    deadline: "2026-07-15",
    eligibility: {
      industries: ["technology", "retail", "manufacturing", "healthcare", "food", "services"],
      maxEmployees: 50,
      maxRevenue: 500000,
      states: "all",
      minorityOwned: true,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: true,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://nmsdc.org/programs/emerging-young-entrepreneurs/",
    tips: [
      "Entrepreneurs must be between 18-35 years old",
      "Minority certification required",
      "Strong mentorship component — be open to guidance",
      "Demonstrate entrepreneurial drive and innovation",
    ],
    commonQuestions: [
      "What inspired you to start your business?",
      "How would mentorship help accelerate your growth?",
      "Describe your business's competitive advantage.",
    ],
    category: "Minority-Owned",
  },
  {
    id: "amber-grant",
    name: "Amber Grant for Women",
    agency: "WomensNet",
    description:
      "Monthly and annual grants for women-owned businesses. Each month one recipient receives funding, with a larger annual grant awarded from the monthly winners.",
    amountMin: 10000,
    amountMax: 25000,
    deadline: "2026-12-31",
    eligibility: {
      industries: ["technology", "retail", "manufacturing", "healthcare", "food", "services", "education", "nonprofit", "construction", "agriculture", "energy"],
      maxEmployees: null,
      maxRevenue: null,
      states: "all",
      minorityOwned: false,
      womenOwned: true,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: true,
      requiresVeteran: false,
    },
    url: "https://ambergrantsforwomen.com/",
    tips: [
      "Application is straightforward — tell your story compellingly",
      "Monthly deadlines — apply early for more chances",
      "Judges look for passion and clear business vision",
      "Follow up on social media to increase visibility",
    ],
    commonQuestions: [
      "Tell us about your business and what makes it special.",
      "How would this grant help your business grow?",
      "What are your goals for the next 12 months?",
    ],
    category: "Women-Owned",
  },
  {
    id: "ifw-grant",
    name: "IFundWomen Universal Grant",
    agency: "IFundWomen",
    description:
      "Rolling grants for women entrepreneurs across all industries. Provides both funding and coaching to help women-led businesses scale.",
    amountMin: 1000,
    amountMax: 25000,
    deadline: "2026-12-31",
    eligibility: {
      industries: ["technology", "retail", "manufacturing", "healthcare", "food", "services", "education"],
      maxEmployees: 100,
      maxRevenue: 2000000,
      states: "all",
      minorityOwned: false,
      womenOwned: true,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: true,
      requiresVeteran: false,
    },
    url: "https://ifundwomen.com/grants",
    tips: [
      "Create a compelling video pitch",
      "Leverage the coaching resources offered alongside the grant",
      "Show traction and early revenue if possible",
      "Build your IFundWomen profile completely before applying",
    ],
    commonQuestions: [
      "Describe your business in 2-3 sentences.",
      "What milestone will this grant help you achieve?",
      "Share your traction or early results.",
    ],
    category: "Women-Owned",
  },
  {
    id: "vetbiz-boost",
    name: "Veteran Business Outreach Center Grants",
    agency: "SBA Veterans Business Outreach Center",
    description:
      "Supports veteran entrepreneurs through training, counseling, and grant funding for business development and startup costs.",
    amountMin: 5000,
    amountMax: 50000,
    deadline: "2026-10-31",
    eligibility: {
      industries: ["technology", "retail", "manufacturing", "healthcare", "food", "services", "construction"],
      maxEmployees: 100,
      maxRevenue: 2000000,
      states: "all",
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: true,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: true,
    },
    url: "https://www.sba.gov/local-assistance/resource-partners/veterans-business-outreach-center-vboc-program",
    tips: [
      "Must provide DD-214 or equivalent documentation",
      "Connect with your local VBOC for pre-application support",
      "Highlight how military experience translates to business skills",
      "Service-disabled veterans may qualify for additional programs",
    ],
    commonQuestions: [
      "Describe your military service and how it prepared you for business ownership.",
      "What is your business plan and how will funds be used?",
      "How will your business serve the veteran community?",
    ],
    category: "Veteran-Owned",
  },
  {
    id: "boots2business",
    name: "Boots to Business Reboot Grant",
    agency: "SBA Office of Veterans Business Development",
    description:
      "Post-service entrepreneurship program with grant funding for veterans transitioning from military to business ownership.",
    amountMin: 2500,
    amountMax: 25000,
    deadline: "2026-12-31",
    eligibility: {
      industries: ["technology", "retail", "manufacturing", "healthcare", "food", "services", "construction", "agriculture"],
      maxEmployees: 25,
      maxRevenue: 500000,
      states: "all",
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: true,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: true,
    },
    url: "https://www.sba.gov/sba-learning-platform/boots-business",
    tips: [
      "Complete the Boots to Business course first",
      "Ideal for recently transitioned veterans",
      "Mentorship connections are a major benefit",
      "Keep your pitch focused and mission-driven",
    ],
    commonQuestions: [
      "When did you transition from military service?",
      "Describe your business concept and target market.",
      "What training or preparation have you completed?",
    ],
    category: "Veteran-Owned",
  },
  {
    id: "ca-small-biz",
    name: "California Small Business COVID-19 Relief Grant",
    agency: "California Office of the Small Business Advocate",
    description:
      "State-funded grants for California small businesses and nonprofits impacted by the pandemic, with ongoing relief rounds for economic recovery.",
    amountMin: 5000,
    amountMax: 25000,
    deadline: "2026-06-30",
    eligibility: {
      industries: ["technology", "retail", "manufacturing", "healthcare", "food", "services", "education", "nonprofit"],
      maxEmployees: 50,
      maxRevenue: 2500000,
      states: ["CA"],
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://calosba.ca.gov/",
    tips: [
      "Must be based in California",
      "Priority for businesses in low-wealth communities",
      "Document revenue decline clearly",
      "Apply early — funds are distributed in rounds",
    ],
    commonQuestions: [
      "Describe your California-based business operations.",
      "How has your business been impacted economically?",
      "What will the grant funds be used for?",
    ],
    category: "State - California",
  },
  {
    id: "tx-enterprise-fund",
    name: "Texas Enterprise Fund",
    agency: "Office of the Texas Governor",
    description:
      "Deal-closing fund used to attract and retain businesses in Texas. Offers grants for job creation and capital investment in the state.",
    amountMin: 50000,
    amountMax: 500000,
    deadline: "2026-12-31",
    eligibility: {
      industries: ["technology", "manufacturing", "healthcare", "energy", "construction"],
      maxEmployees: 500,
      maxRevenue: 10000000,
      states: ["TX"],
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://gov.texas.gov/business/page/texas-enterprise-fund",
    tips: [
      "Must commit to job creation in Texas",
      "Strong ROI narrative is essential",
      "Local government support letter strengthens application",
      "Demonstrate why Texas is the right location for your business",
    ],
    commonQuestions: [
      "How many jobs will your business create in Texas?",
      "What capital investment are you planning?",
      "Why is Texas the ideal location for your business?",
    ],
    category: "State - Texas",
  },
  {
    id: "ny-esd-grant",
    name: "New York Empire State Development Grant",
    agency: "Empire State Development",
    description:
      "Grants for businesses creating jobs and making capital investments in New York State. Supports economic growth in all regions of the state.",
    amountMin: 25000,
    amountMax: 250000,
    deadline: "2026-09-30",
    eligibility: {
      industries: ["technology", "manufacturing", "healthcare", "food", "services", "energy"],
      maxEmployees: 200,
      maxRevenue: 5000000,
      states: ["NY"],
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://esd.ny.gov/business-programs",
    tips: [
      "Emphasize job creation and retention in New York",
      "Regional economic development councils can support your application",
      "Matching funds may be available",
      "Highlight community and workforce development impact",
    ],
    commonQuestions: [
      "Describe your business's presence in New York State.",
      "What economic impact will your project have?",
      "How many jobs will be created or retained?",
    ],
    category: "State - New York",
  },
  {
    id: "fl-rural-grant",
    name: "Florida Rural Community Development Grant",
    agency: "Florida Department of Economic Opportunity",
    description:
      "Grants for businesses in rural Florida communities to support economic development, infrastructure, and job creation.",
    amountMin: 10000,
    amountMax: 150000,
    deadline: "2026-08-15",
    eligibility: {
      industries: ["agriculture", "manufacturing", "healthcare", "food", "services", "construction"],
      maxEmployees: 100,
      maxRevenue: 3000000,
      states: ["FL"],
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://floridajobs.org/community-planning-and-development/community-development/rural-community-development",
    tips: [
      "Must be in a designated rural area of Florida",
      "Community impact is a key evaluation criterion",
      "Partner with local economic development organizations",
      "Infrastructure improvements can be included in the proposal",
    ],
    commonQuestions: [
      "Describe your business's location and rural community.",
      "How will this project benefit the rural community?",
      "What partnerships do you have with local organizations?",
    ],
    category: "State - Florida",
  },
  {
    id: "usda-value-added",
    name: "USDA Value-Added Producer Grant",
    agency: "U.S. Department of Agriculture",
    description:
      "Helps agricultural producers create value-added products, enter new markets, and develop business plans for value-added ventures.",
    amountMin: 25000,
    amountMax: 250000,
    deadline: "2026-04-30",
    eligibility: {
      industries: ["agriculture", "food"],
      maxEmployees: 300,
      maxRevenue: 5000000,
      states: "all",
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://www.rd.usda.gov/programs-services/business-programs/value-added-producer-grants",
    tips: [
      "Must be an agricultural producer (farmer, rancher, harvester)",
      "Value-added means changing physical state or production manner",
      "Matching funds required (1:1 cash match)",
      "Working capital and planning grants available",
    ],
    commonQuestions: [
      "Describe your agricultural operation and value-added product.",
      "What market opportunity exists for your product?",
      "How will you match the grant funds?",
    ],
    category: "Federal - USDA",
  },
  {
    id: "doe-clean-energy",
    name: "DOE Small Business Clean Energy Grant",
    agency: "U.S. Department of Energy",
    description:
      "Supports small businesses developing clean energy technologies including solar, wind, battery storage, and energy efficiency solutions.",
    amountMin: 100000,
    amountMax: 2000000,
    deadline: "2026-07-31",
    eligibility: {
      industries: ["technology", "energy", "manufacturing"],
      maxEmployees: 500,
      maxRevenue: null,
      states: "all",
      minorityOwned: false,
      womenOwned: false,
      veteranOwned: false,
      requiresMinority: false,
      requiresWomen: false,
      requiresVeteran: false,
    },
    url: "https://www.energy.gov/clean-energy/small-business",
    tips: [
      "Strong technical team credentials are essential",
      "Demonstrate environmental impact and carbon reduction",
      "Include commercialization pathway",
      "DOE values partnerships with national labs",
    ],
    commonQuestions: [
      "Describe the clean energy technology and its innovation.",
      "What is the potential environmental impact?",
      "Outline your commercialization and scale-up plan.",
    ],
    category: "Federal - DOE",
  },
];
