const API = "http://localhost:3000/api/generate";
const tests: { name: string; body: Record<string, unknown>; status: number; validate?: (d: Record<string, unknown>) => string | null }[] = [
  { name: "generates 2-tier pricing page", body: { productName: "Acme", tiers: [{ name: "Free", price: "$0", period: "forever", features: ["1 user"], highlighted: false }, { name: "Pro", price: "$29", period: "/mo", features: ["Unlimited users", "Priority support"], highlighted: true }], accentColor: "#8b5cf6", style: "cards" }, status: 200, validate: (d) => { const h = d.html as string; if (!h.includes("Acme")) return "Missing product name"; if (!h.includes("$29")) return "Missing price"; return null; } },
  { name: "generates 4-tier max", body: { productName: "Test", tiers: [{ name: "A", price: "$1", period: "/mo", features: [], highlighted: false }, { name: "B", price: "$2", period: "/mo", features: [], highlighted: false }, { name: "C", price: "$3", period: "/mo", features: [], highlighted: true }, { name: "D", price: "$4", period: "/mo", features: [], highlighted: false }], accentColor: "#fff", style: "minimal" }, status: 200 },
  { name: "rejects empty tiers", body: { productName: "Test", tiers: [], accentColor: "#fff", style: "cards" }, status: 400 },
  { name: "rejects 5+ tiers", body: { productName: "Test", tiers: Array(5).fill({ name: "T", price: "$1", period: "/mo", features: [], highlighted: false }), accentColor: "#fff", style: "cards" }, status: 400 },
  { name: "rejects invalid style", body: { productName: "Test", tiers: [{ name: "A", price: "$1", period: "/mo", features: [], highlighted: false }], accentColor: "#fff", style: "fancy" }, status: 400 },
];
async function run() { let p = 0, f = 0; for (const t of tests) { try { const r = await fetch(API, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(t.body) }); if (r.status !== t.status) { console.error(`FAIL: ${t.name} — expected ${t.status}, got ${r.status}`); f++; continue; } if (t.status === 200 && t.validate) { const d = await r.json(); const e = t.validate(d); if (e) { console.error(`FAIL: ${t.name} — ${e}`); f++; continue; } } console.log(`PASS: ${t.name}`); p++; } catch (e) { console.error(`FAIL: ${t.name} — ${e}`); f++; } } console.log(`\n${p}/${p + f} tests passed`); if (f > 0) process.exit(1); } run();
